# Changing the workflow name will reset the run number
name: Build on PR

on:
  pull_request:
    branches:
    - develop

env:
  MAJOR: 12
  MINOR: 1
  RUN: ${{ github.run_number }}
  WIX: "C:/Program Files (x86)/WiX Toolset v3.14"

jobs:

  latest-pksim:
    uses: ./.github/workflows/latest-artifact.yml
    with:
      repo-name: PK-Sim
      action-name: build-nightly.yml
      artifact-pattern: PKSim Installer
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  latest-mobi:
    uses: ./.github/workflows/latest-artifact.yml
    with:
      repo-name: MoBi
      action-name: build-nightly.yml
      artifact-pattern: MoBi Installer
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  latest-validator:
    uses: ./.github/workflows/latest-artifact.yml
    with:
      repo-name: InstallationValidator
      action-name: build-nightly.yml
      artifact-pattern: Installation Validator Installer
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-nightly:
    runs-on: windows-latest
    needs: [latest-pksim, latest-mobi, latest-validator]
    steps:
      - name: Download PK-Sim Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.latest-pksim.outputs.artifact-name }}
          path: ./deploy/pk-sim
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: Open-Systems-Pharmacology/PK-Sim
          run-id: ${{ needs.latest-pksim.outputs.run-id }}

      - name: Download MoBi Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.latest-mobi.outputs.artifact-name }}
          path: ./deploy/mobi
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: Open-Systems-Pharmacology/MoBi
          run-id: ${{ needs.latest-mobi.outputs.run-id }}

      - name: Download Validator Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.latest-validator.outputs.artifact-name }}
          path: ./deploy/installationvalidator
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: Open-Systems-Pharmacology/InstallationValidator
          run-id: ${{ needs.latest-validator.outputs.run-id }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: download requirements
        run: |
          (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=863265', './netfx472.exe')
          (new-object net.webclient).DownloadFile('https://aka.ms/vs/17/release/vc_redist.x64.exe', './vc_redist.x64.exe')
          (new-object net.webclient).DownloadFile('https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi', './MikTex.msi')

          
      - name: Create Portable Setup
        run: |
          rake "create_setup[${{env.APP_VERSION}}]"
