# Changing the workflow name will reset the run number
name: Build Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

env:
  WIX: "C:/Program Files (x86)/WiX Toolset v3.14"
  APP_VERSION: 12.2.${{ github.run_number }}

permissions:
  contents: read
  packages: read

jobs:
  latest-pksim:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/latest-artifact.yml@main
    with:
      repo-name: PK-Sim
      action-name: build-nightly_12.2.yml
      artifact-pattern: PKSim Installer
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  latest-mobi:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/latest-artifact.yml@main
    with:
      repo-name: MoBi
      action-name: build-nightly_12.2.yml
      artifact-pattern: MoBi Installer
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  latest-validator:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/latest-artifact.yml@main
    with:
      repo-name: InstallationValidator
      action-name: build-nightly.yml
      artifact-pattern: Installation Validator Installer
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-installers:
    runs-on: windows-latest
    needs: [latest-pksim, latest-mobi, latest-validator]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Download PK-Sim Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.latest-pksim.outputs.artifact-name }}
          path: ./deploy/pk-sim
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: Open-Systems-Pharmacology/PK-Sim
          run-id: ${{ needs.latest-pksim.outputs.run-id }}

      - name: Download MoBi Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.latest-mobi.outputs.artifact-name }}
          path: ./deploy/mobi
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: Open-Systems-Pharmacology/MoBi
          run-id: ${{ needs.latest-mobi.outputs.run-id }}

      - name: Download Validator Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.latest-validator.outputs.artifact-name }}
          path: ./deploy/installationvalidator
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: Open-Systems-Pharmacology/InstallationValidator
          run-id: ${{ needs.latest-validator.outputs.run-id }}

      - name: Download Requirements
        run: |
          (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=863265', './netfx472.exe')
          (new-object net.webclient).DownloadFile('https://aka.ms/vs/17/release/vc_redist.x64.exe', './vc_redist.x64.exe')
          (new-object net.webclient).DownloadFile('https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi', './MikTex.msi')

      - name: Create Setup
        run: |
          rake "create_setup[${{env.APP_VERSION}}]"

      # Sign the setup with the certificate. For a WIX bundle, it requires several steps:
      # (s. https://docs.firegiant.com/wix3/overview/insignia/)
      # 
      # 1. Extract the burn engine from the bundle
      # 2. Sign the burn engine with the certificate
      # 3. Re-Attach the burn engine to the bundle
      # 4. Sign the bundle with the certificate
      - name: Extract Wix Burn Engine
        shell: cmd
        run: |
          insignia -ib ./output/OSPSuite-Full.${{env.APP_VERSION}}.exe -o burnengine.exe

      - name: Sign Wix burn engine with CodeSignTool
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/codesigner-SSL@main
        env:
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
        with:
          file_path: ./burnengine.exe

      - name: Reattach signed Wix Burn engine to the Bundle
        shell: cmd
        run: |
          ren output\OSPSuite-Full.${{env.APP_VERSION}}.exe original_OSPSuite-Full.${{env.APP_VERSION}}.exe
          insignia -ab burnengine.exe output\original_OSPSuite-Full.${{env.APP_VERSION}}.exe -o output\OSPSuite-Full.${{env.APP_VERSION}}.exe
          del output\original_OSPSuite-Full.${{env.APP_VERSION}}.exe

      - name: Sign Suite Setup with CodeSignTool
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/codesigner-SSL@main
        env:
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
        with:
          file_path: ./output/OSPSuite-Full.${{env.APP_VERSION}}.exe

      - name: Push full as artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSPSuite Full Installer ${{env.APP_VERSION}}
          path: output\OSPSuite-Full.${{env.APP_VERSION}}.exe
