# Changing the workflow name will reset the run number
name: Build on PR

on:
  pull_request:
    branches:
    - develop

env:
  MAJOR: 12
  MINOR: 1
  RUN: ${{ github.run_number }}

jobs:
  build-nightly:
    needs: download-latest-successful-artifact
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: download requirements
        run: |
          (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=863265', './netfx472.exe')
          (new-object net.webclient).DownloadFile('https://aka.ms/vs/17/release/vc_redist.x64.exe', './vc_redist.x64.exe')
          (new-object net.webclient).DownloadFile('https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi', './MikTex.msi')
      
      # - name: Create Portable Setup
      #   run: |
      #     rake "create_setup[${{env.APP_VERSION}}]"

  download-latest-successful-artifact:
   runs-on: ubuntu-latest

   steps:
     # Step 1: Get the latest successful workflow run of Build-Nightly in RepoA
     - name: Get Latest Successful Run
       id: get-run
       uses: octokit/request-action@v2.1.0
       with:
         route: GET /repos/Open-Systems-Pharmacology/PK-Sim/actions/workflows/build-nightly.yml/runs?status=success
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     

     # Step 2: List the artifacts for the latest successful run
     - name: List Artifacts
       id: list-artifacts
       uses: octokit/request-action@v2.1.0
       with:
         route: GET /repos/Open-Systems-Pharmacology/PK-Sim/actions/runs/${{ fromJson(steps.get-run.outputs.data).workflow_runs[0].id }}/artifacts
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
     # Step 3: Filter artifacts to find the one starting with "PKSim Installer"
     - name: Find Matching Artifact
       id: find-artifact
       run: |
         echo "Artifacts from the run: '${{ steps.list-artifacts.outputs.data }}'"
         ARTIFACT_NAME=$(echo '${{ steps.list-artifacts.outputs.data }}' | jq -r '.artifacts[] | select(.name | startswith("PKSim Installer")) | .name')
         echo "Artifact Name: $ARTIFACT_NAME"
         echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_ENV

     # Step 4: Download the artifact
     - name: Download Artifact
       uses: actions/download-artifact@v4
       with:
         name: ${{ env.artifact_name }}
         path: ./artifacts