name: Check Markdown links

on: 
  pull_request:
    branches:
      - develop
 
jobs:
  markdown-link-check:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/MarkdownLinksCheck.yml@main

